# Quick boot options
sudo: false
cache: yarn

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - 6
  - 8
  - 9
  - 10
arch:
  - amd64
  - ppc64le
script:
  - yarn test
  - yarn lint

# Npm publish options
before_deploy:
  - rm .gitignore
  - yarn build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: CMFF6dnRAVd6EPWfEOdsFSgY3XQxEDS0TYyvIDt2Xy9eaGaFq4jwdpCQ+9OZNGfDXcmBjuDXnsWv6TqxYHohm5hLYYqU1CT1fFVUU0sCxl41HKyliXUC21qaT/lB68EcRSnDAdCAcQ/jLFIZObBxwHD7yUOyoBnmkTvcBn5Kgi6kaKYjJlzP4Z0zP0MbO3+2R2LTj01eAcE7TtHehITcP4CktPGRkDLgRjFmOahg63MnfpsqHX22p/l/Z3OqCnguhHK6b7cpjwHL4zfyEHU/K+o6KsLErFidIAg1yKzFskaHUImVYQiJhkJaJyzA9YW4xW1UYHjO1BwxkxsJOM0EMbzWxH8hEvrig6wgP8Midp3RXWusJ8VbZvNcyj4OPYWhc4aR5GOlr7W36xp04d0BP+WZVBycxYVbMFj5SmbF6BXjeC6w1Aj3m+oUUIC5SUKwDD3hyfgCrBoAGcKhKxRF9SGUWdHSouuisuFWTSdFiUugBPrYx+LhBVVkByLAvy1J7j+yl03I08X4/N6c4mJ2e6eE7B02oaS4tTyJT8BADJ7pE6vG4r3T+qRy7rqU4SHJ4pwzG2AyuvwxeTwz7PCSWFD/XgQgd2qROLpekT4Ds8v9TPt4vSfWgN4otIIRV91UcLvBBmlERCHwcwmX4iU3p7tYMVhcdrhI9FpDNNK/4J0=
  on:
    node: 6
    repo: 59naga/babel-plugin-add-module-exports
